# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-27 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_procedures', '0003_finalregistrations_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistrationcheck',
            name='semester',
            field=models.IntegerField(default=1),
        ),
    ]
