# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-27 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_procedures', '0006_feepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='transaction_id',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
