# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-27 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0004_curriculum_floated'),
        ('academic_procedures', '0008_auto_20190327_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='batch',
            field=models.IntegerField(default=2016),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='semester',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='student_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academic_information.Student'),
            preserve_default=False,
        ),
    ]
