# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-04 05:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0005_grades_verify'),
        ('academic_procedures', '0011_teachingcreditregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingcreditregistration',
            name='approved_course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teachingcreditregistration_approved_course', to='academic_information.Curriculum'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teachingcreditregistration',
            name='course_completion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teachingcreditregistration',
            name='req_pending',
            field=models.BooleanField(default=True),
        ),
    ]
