# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-04 05:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0001_initial'),
        ('academic_procedures', '0012_auto_20190404_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingcreditregistration',
            name='supervisor_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teachingcreditregistration_supervisor_id', to='globals.Faculty'),
            preserve_default=False,
        ),
    ]
