# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-04 05:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_procedures', '0013_teachingcreditregistration_supervisor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachingcreditregistration',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='teachingcreditregistration',
            name='name',
        ),
    ]
