# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-04 06:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_procedures', '0014_auto_20190404_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachingcreditregistration',
            name='approved_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachingcreditregistration_approved_course', to='academic_information.Curriculum'),
        ),
        migrations.AlterField(
            model_name='teachingcreditregistration',
            name='supervisor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachingcreditregistration_supervisor_id', to='globals.Faculty'),
        ),
    ]
