# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-12 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0007_auto_20190404_1425'),
        ('academic_procedures', '0015_auto_20190404_0605'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.FloatField(default=None)),
                ('mid_term', models.FloatField(default=None)),
                ('q2', models.FloatField(default=None)),
                ('end_term', models.FloatField(default=None)),
                ('other', models.FloatField(default=None)),
                ('grade', models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D+', 'D+'), ('D', 'D'), ('F', 'F')], max_length=5)),
                ('curr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.Curriculum')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.Student')),
            ],
            options={
                'db_table': 'SemesterMarks',
            },
        ),
    ]
