# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-12 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_procedures', '0016_semestermarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='semestermarks',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
