# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-13 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_procedures', '0017_semestermarks_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestermarks',
            name='grade',
            field=models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D+', 'D+'), ('D', 'D'), ('F', 'F')], max_length=5, null=True),
        ),
    ]
