# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-18 11:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_procedures', '0019_marksubmissioncheck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semestermarks',
            name='verified',
        ),
    ]
