# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-21 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_procedures', '0020_remove_semestermarks_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='marksubmissioncheck',
            name='announced',
            field=models.BooleanField(default=False),
        ),
    ]
