# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-09-26 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_procedures', '0021_marksubmissioncheck_announced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestermarks',
            name='grade',
            field=models.CharField(choices=[('O', 'O'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D+', 'D+'), ('D', 'D'), ('F', 'F'), ('S', 'S'), ('X', 'X')], max_length=5, null=True),
        ),
    ]
