# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-09-26 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchSemester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.IntegerField(default=2019)),
                ('semester', models.IntegerField(default=0)),
                ('programme', models.CharField(choices=[('BTECH', 'BTech'), ('BDES', 'BDes'), ('MTech', 'MTech'), ('MDes', 'MDes'), ('PhD', 'PhD')], default='', max_length=30)),
                ('total_number_of_courses', models.IntegerField(default=0)),
                ('professional_core_courses', models.IntegerField(default=0)),
                ('professional_elective_courses', models.IntegerField(default=0)),
                ('professional_project_courses', models.IntegerField(default=0)),
                ('professional_lab_courses', models.IntegerField(default=0)),
                ('Core_engineering_science_courses', models.IntegerField(default=0)),
                ('Core_natural_science_courses', models.IntegerField(default=0)),
                ('Core_humanities_courses', models.IntegerField(default=0)),
                ('Core_design_courses', models.IntegerField(default=0)),
                ('Core_manufacturing_courses', models.IntegerField(default=0)),
                ('Core_management_science_courses', models.IntegerField(default=0)),
                ('pbi', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BtechCurriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme', models.CharField(choices=[('BTECH', 'BTech'), ('BDES', 'BDes'), ('MTech', 'MTech'), ('MDes', 'MDes'), ('PhD', 'PhD')], max_length=30)),
                ('batch', models.IntegerField(default=2019)),
                ('professional_core_credit', models.IntegerField(default=0)),
                ('professional_elective_credit', models.IntegerField(default=0)),
                ('professional_project_credit', models.IntegerField(default=0)),
                ('professional_lab_credit', models.IntegerField(default=0)),
                ('Core_engineering_science_credit', models.IntegerField(default=0)),
                ('Core_natural_science_credit', models.IntegerField(default=0)),
                ('Core_humanities_credit', models.IntegerField(default=0)),
                ('Core_design_credit', models.IntegerField(default=0)),
                ('Core_manufacturing_credit', models.IntegerField(default=0)),
                ('Core_management_science_credit', models.IntegerField(default=0)),
                ('pbi', models.IntegerField(default=0)),
                ('pr', models.IntegerField(default=0)),
                ('sem1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Semester1', to='acad.BatchSemester')),
                ('sem2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Semester2', to='acad.BatchSemester')),
                ('sem3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Semester3', to='acad.BatchSemester')),
                ('sem4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Semester4', to='acad.BatchSemester')),
                ('sem5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Semester5', to='acad.BatchSemester')),
                ('sem6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Semester6', to='acad.BatchSemester')),
                ('sem7', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Semester7', to='acad.BatchSemester')),
                ('sem8', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Semester8', to='acad.BatchSemester')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=256, unique=True)),
                ('course_details', models.TextField(max_length=2500)),
            ],
        ),
        migrations.CreateModel(
            name='CurriculumCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(blank=True, max_length=20, null=True)),
                ('course_type', models.CharField(blank=True, choices=[('Core', 'Professional Core'), ('Elective', 'Professional Elective'), ('Lab', 'Professional Lab'), ('Project', 'Professional Project'), ('ES', 'Engineering Science'), ('NS', 'Natural Science'), ('HS', 'Humanities'), ('DS', 'Design'), ('MN', 'Manufacturing'), ('MS', 'Management Science')], max_length=200, null=True)),
                ('course_credits', models.IntegerField(default=0)),
                ('course_lecture', models.IntegerField(default=0)),
                ('course_tutorial', models.IntegerField(default=0)),
                ('course_practical', models.IntegerField(default=0)),
                ('course_discussion', models.IntegerField(default=0)),
                ('curr_course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='acad.Course')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='acad.BatchSemester')),
            ],
        ),
        migrations.CreateModel(
            name='CurriculumInstructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor', models.CharField(max_length=256, null=True)),
                ('head_instructor', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acad.CurriculumCourse')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='curriculuminstructor',
            unique_together=set([('course', 'instructor')]),
        ),
        migrations.AlterUniqueTogether(
            name='curriculumcourse',
            unique_together=set([('semester', 'course_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='btechcurriculum',
            unique_together=set([('programme', 'batch')]),
        ),
    ]
