# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-09-30 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='btechcurriculum',
            name='total_credits',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='curriculumcourse',
            name='branch',
            field=models.CharField(blank=True, choices=[('CSE', 'Computer Science and Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('ME', 'Mechanical Engineering'), ('Btech_ALL', 'Btech All'), ('Common', 'Common'), ('DES', 'Design')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='batchsemester',
            name='programme',
            field=models.CharField(choices=[('BTECH', 'BTECH'), ('BDES', 'BDES'), ('MTECH', 'MTECH'), ('MDES', 'MDES'), ('PHD', 'PHD')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='btechcurriculum',
            name='programme',
            field=models.CharField(choices=[('BTECH', 'BTECH'), ('BDES', 'BDES'), ('MTECH', 'MTECH'), ('MDES', 'MDES'), ('PHD', 'PHD')], max_length=30),
        ),
    ]
