# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-10-21 22:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acad', '0002_auto_20190930_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='MtechCurriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.IntegerField(default=2019)),
                ('programme', models.CharField(choices=[('BTECH', 'BTECH'), ('BDES', 'BDES'), ('MTECH', 'MTECH'), ('MDES', 'MDES'), ('PHD', 'PHD')], default='', max_length=30)),
                ('total_number_of_courses', models.IntegerField(default=0)),
                ('branch', models.CharField(blank=True, choices=[('CSE', 'Computer Science and Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('ME', 'Mechanical Engineering'), ('Btech_ALL', 'Btech All'), ('Common', 'Common'), ('DES', 'Design')], max_length=25, null=True)),
                ('specialization', models.CharField(blank=True, choices=[('Power and Control', 'Power and Control'), ('Microwave and Communication Engineering', 'Microwave and Communication Engineering'), ('Micro-nano Electronics', 'Micro-nano Electronics'), ('CAD/CAM', 'CAD/CAM'), ('Design', 'Design'), ('Manufacturing', 'Manufacturing'), ('CSE', 'CSE'), ('Mechatronics', 'Mechatronics'), ('MDes', 'MDes'), ('all', 'all')], max_length=50, null=True)),
                ('total_credits', models.IntegerField(default=0)),
                ('elective_credits', models.IntegerField(default=0)),
                ('lab_credits', models.IntegerField(default=0)),
                ('thesis_credits', models.IntegerField(default=0)),
                ('seminar_credits', models.IntegerField(default=0)),
                ('core_credits', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MtechSemester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.IntegerField(default=2019)),
                ('programme', models.CharField(choices=[('BTECH', 'BTECH'), ('BDES', 'BDES'), ('MTECH', 'MTECH'), ('MDES', 'MDES'), ('PHD', 'PHD')], default='', max_length=30)),
                ('semester', models.IntegerField(default=0)),
                ('total_courses', models.IntegerField(default=0)),
                ('elective_courses', models.IntegerField(default=0)),
                ('core_courses', models.IntegerField(default=0)),
                ('thesis', models.IntegerField(default=0)),
                ('seminar', models.IntegerField(default=0)),
                ('lab_courses', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='mtechcurriculum',
            name='sem1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mtech_semester_1', to='acad.MtechSemester'),
        ),
        migrations.AddField(
            model_name='mtechcurriculum',
            name='sem2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mtech_semester_2', to='acad.MtechSemester'),
        ),
        migrations.AddField(
            model_name='mtechcurriculum',
            name='sem3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mtech_semester_3', to='acad.MtechSemester'),
        ),
        migrations.AddField(
            model_name='mtechcurriculum',
            name='sem4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mtech_semester_4', to='acad.MtechSemester'),
        ),
    ]
