# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-11-07 11:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acad', '0005_curriculumcourse_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculumcourse',
            name='batch',
        ),
    ]
