# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-11-08 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acad', '0006_remove_curriculumcourse_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumcourse',
            name='mtech_semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='acad.MtechSemester'),
        ),
    ]
