# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-04 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0005_grades_verify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='course_code',
            field=models.CharField(max_length=25),
        ),
    ]
