# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-04 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0006_auto_20190404_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='course_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='course_type',
            field=models.CharField(choices=[('Professional Core', 'Professional Core'), ('Professional Elective', 'Professional Elective'), ('Professional Lab', 'Professional Lab'), ('Engineering Science', 'Engineering Science'), ('Natural Science', 'Natural Science'), ('Humanities', 'Humanities'), ('Design', 'Design'), ('Manufacturing', 'Manufacturing'), ('Management Science', 'Management Science')], max_length=25),
        ),
    ]
