# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-13 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0007_auto_20190404_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum_instructor',
            name='chief_inst',
            field=models.BooleanField(default=False),
        ),
    ]
