# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-28 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0009_auto_20190428_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='branch',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('ME', 'ME'), ('DESIGN', 'DESIGN'), ('Common', 'Common')], default='Common', max_length=10),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='branch',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('ME', 'ME'), ('DESIGN', 'DESIGN'), ('Common', 'Common')], default='Common', max_length=10),
        ),
    ]
