# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-28 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0010_auto_20190428_1507'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='curriculum',
            unique_together=set([('course_code', 'batch', 'programme')]),
        ),
    ]
